version: '3'
services:

  app:
    image: amazoncorretto:17-alpine
    ports:
      - "8080:8080"

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: demo_app
      MYSQL_ROOT_PASSWORD: demo_pass
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest

volumes:
 mysql_data:








































